### ISSUE TITLE
Maintenence

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-contrib/cheeseshop#2]
Hi @sallner -- please could I request permissions on this repository and on PyPI? I'd like to update this repo to remove the jQuery dependency and update to PEP 420 packaging, as I have been with the Sphinx first-party sphinx-contrib packages.

Thanks,
Adam

**Comment by sallner** [comment]
@AA-Turner sorry for the late reply. I will do that.

**Comment by sallner** [comment]
@AA-Turner I added an invitation to this repository and to the PyPI for you. please accept them.

**Comment by sallner** [comment]
As the version was released on PyPI, I am closing this issue now.
